name: PR CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2

      # clippy::all doesn't include pedantic btw
      - name: Cargo Clippy
        run: cargo clippy --release -- -D warnings --warn clippy::all

      - name: Cargo Check
        run: cargo check --release

      - name: Cargo Test
        run: cargo test --release
